name: Check

on:
  pull_request:
  push:
    branches: [main]

env:
  CARGO_INCREMENTAL: 0
  RUSTFLAGS: -D warnings
  # For setup-rust
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        name:
          - linux-x86-64-gnu
          - mac-x86-64
        include:
          - name: linux-x86-64-gnu
            os: ubuntu-22.04
          - name: mac-x86-64
            os: macos-latest

    name: Binaries for ${{ matrix.name }}
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v5
        with:
          submodules: recursive
          persist-credentials: false
      - uses: moonrepo/setup-rust@v1
      - name: Test
        run: cargo test

  pre-commit:
    name: Run pre-commit hooks
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v5
        with:
          submodules: recursive
          persist-credentials: false
      - uses: moonrepo/setup-rust@v1
        with:
          components: clippy,rustfmt
      - uses: actions/setup-python@v6
      - uses: pre-commit/action@v3.0.1
